# Generated by Django 3.2.16 on 2023-08-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_auto_20230813_2221'),
        ('ice_cream', '0004_alter_icecream_options'),
    ]

    operations = [
    ]
